In [1]:
import numpy as np

In [2]:
A = np.array([[1, 1/30, 0], 
              [0, 1, 0.1], 
              [0, 0, 1.1]])

In [4]:
eig_obj = np.linalg.eig(A)

In [5]:
#Eigenvalues
eig_obj[0]

array([1. , 1. , 1.1])

In [6]:
#Eigenvectors
eig_obj[1]

array([[ 1.00000000e+00, -1.00000000e+00,  2.29415734e-01],
       [ 0.00000000e+00,  6.66133815e-15,  6.88247202e-01],
       [ 0.00000000e+00,  0.00000000e+00,  6.88247202e-01]])

In [9]:
B = np.array([0, 1, -1]).reshape(3, 1)
B

array([[ 0],
       [ 1],
       [-1]])

In [11]:
np.linalg.matrix_power(A, 500) @ B

array([[-1.65661399e+20],
       [-4.96984197e+20],
       [-4.96984197e+20]])

In [12]:
np.linalg.matrix_power(A, 500).dot(B)

array([[-1.65661399e+20],
       [-4.96984197e+20],
       [-4.96984197e+20]])

In [20]:
C = np.array([[0.5, 1/30, 0], 
              [0, 0.5, 0.1], 
              [0, 0, 0.9]])

In [21]:
np.linalg.eig(C)

(array([0.5, 0.5, 0.9]),
 array([[ 1.00000000e+00, -1.00000000e+00,  2.02071752e-02],
        [ 0.00000000e+00,  3.33066907e-15,  2.42486103e-01],
        [ 0.00000000e+00,  0.00000000e+00,  9.69944411e-01]]))

In [22]:
D = np.array([0, 1, -1]).reshape(3, 1)
#Because dom. eigenvalue is < 1 then the dom vector will be shrinking
np.linalg.matrix_power(C, 500).dot(D)

array([[-2.75431421e-25],
       [-3.30517705e-24],
       [-1.32207082e-23]])

In [23]:
#To find dominant eiganvalue, find largest abs value.