In [1]:
import numpy as np

### Decisions of the School Board

In [2]:
A_Board = np.array([[1, 1], 
                    [1, 1]])

A_SB = np.array([[1, 0.5], 
                 [2, 1]])


A_SN = np.array([[1, 0.333], 
                 [3, 1]])

In [3]:
# Computes the sum of each column in Matrix A_Board
A_Board_col_weights = A_Board.sum(axis=0)
A_Board_col_weights

array([2, 2])

In [4]:
# Divides each column in Matrix A by the sum of each Column in Matrix A, columnwise.
A_Board_N = A_Board/A_Board_col_weights
A_Board_N

array([[0.5, 0.5],
       [0.5, 0.5]])

In [5]:
# Computes the average of each row in Matrix A_N, and returns a column vector.
# This is the criteria ranking vector.
A_Board_criteria_ranking_vect = (A_Board_N.sum(axis=1)/2).reshape((2,1))
A_Board_criteria_ranking_vect

array([[0.5],
       [0.5]])

In [6]:
A_Board_criteria_ranking_vect.sum()

1.0

In [7]:
def compute_eigen_vector(A):
    # Computes the sum of each column in Matrix A
    A_col_weights = A.sum(axis=0)

    # Divides each column in Matrix AI by the sum of each Column in Matrix AI, columnwise.
    A_N = A/A_col_weights

    # Computes the average of each row in Matrix AI_N, and returns a column vector.
    A_N_row_mean = np.mean(A_N, axis=1)

    # Returns the row vector that shows the mean of each column in AI after it is normalized. 
    return A_N_row_mean

In [8]:
A_SB_N_row_mean = compute_eigen_vector(A=A_SB)
A_SB_N_row_mean

array([0.33333333, 0.66666667])

In [9]:
A_SN_N_row_mean = compute_eigen_vector(A=A_SN)
A_SN_N_row_mean

array([0.24990623, 0.75009377])

In [10]:
A_S_eig_matrix = np.array([A_SB_N_row_mean, A_SN_N_row_mean]).T
A_S_eig_matrix

array([[0.33333333, 0.24990623],
       [0.66666667, 0.75009377]])

In [11]:
# Based on the Board decision, the Music program should be cut. 

Final_Decision_Board = A_S_eig_matrix.dot(A_Board_criteria_ranking_vect)
Final_Decision_Board

array([[0.29161978],
       [0.70838022]])

### Decisions of the Parent-Teacher Assocition

In [12]:
A_Parents = np.array([[1, 0.5], 
                      [2, 1]])

A_PB = np.array([[1, 0.333], 
                 [3, 1]])


A_PN = np.array([[1, 2], 
                 [0.5, 1]])

In [13]:
# Computes the sum of each column in Matrix A_Parents
A_Parents_col_weights = A_Parents.sum(axis=0)
A_Parents_col_weights

array([3. , 1.5])

In [14]:
# Divides each column in Matrix A by the sum of each Column in Matrix A, columnwise.
A_Parents_N = A_Parents/A_Parents_col_weights
A_Parents_N

array([[0.33333333, 0.33333333],
       [0.66666667, 0.66666667]])

In [15]:
# Computes the average of each row in Matrix A_N, and returns a column vector.
# This is the criteria ranking vector.
A_Parents_criteria_ranking_vect = (A_Parents_N.sum(axis=1)/2).reshape((2,1))
A_Parents_criteria_ranking_vect

array([[0.33333333],
       [0.66666667]])

In [16]:
A_Parents_criteria_ranking_vect.sum()

1.0

In [17]:
A_PB_N_row_mean = compute_eigen_vector(A=A_PB)
A_PB_N_row_mean

array([0.24990623, 0.75009377])

In [18]:
A_PN_N_row_mean = compute_eigen_vector(A=A_PN)
A_PN_N_row_mean

array([0.66666667, 0.33333333])

In [19]:
A_P_eig_matrix = np.array([A_PB_N_row_mean, A_PN_N_row_mean]).T
A_P_eig_matrix

array([[0.24990623, 0.66666667],
       [0.75009377, 0.33333333]])

In [20]:
# Based on the Parents decision, the Physical Education (E) program should be cut. 

Final_Decision_Parents = A_P_eig_matrix.dot(A_Parents_criteria_ranking_vect)
Final_Decision_Parents

array([[0.52774652],
       [0.47225348]])

In [21]:
board_weight = 0.5
parents_weight = 0.5

### Final Decision

In [22]:
# Based on the joint decision, the Music program (M) should be cut since it received a higher score. 

final_decision =(Final_Decision_Parents * parents_weight) + (Final_Decision_Board * board_weight)
final_decision

array([[0.40968315],
       [0.59031685]])

In [23]:
# Consistency was not checked since it is guaranteed in a 2x2 matrix.