In [1]:
import numpy as np

### Problem 15-5

In [2]:
A = np.array([[1, 1, 0.25], 
              [1, 1, 0.2], 
              [4, 5, 1]])

AR = np.array([[1, 2], 
               [0.5, 1]])

AM = np.array([[1, 0.5], 
               [2, 1]])

AA = np.array([[1, 1], 
               [1, 1]])

In [3]:
# Computes the sum of each column in Matrix A
A_col_weights = A.sum(axis=0)
A_col_weights

array([6.  , 7.  , 1.45])

In [4]:
# Divides each column in Matrix A by the sum of each Column in Matrix A, columnwise.
A_N = A/A_col_weights
A_N

array([[0.16666667, 0.14285714, 0.17241379],
       [0.16666667, 0.14285714, 0.13793103],
       [0.66666667, 0.71428571, 0.68965517]])

In [5]:
# Computes the average of each row in Matrix A_N, and returns a column vector.
# This is the criteria ranking vector.
A_criteria_ranking_vect = (A_N.sum(axis=1)/3).reshape((3,1))
A_criteria_ranking_vect

array([[0.16064587],
       [0.14915161],
       [0.69020252]])

In [6]:
A_criteria_ranking_vect.sum()

1.0

In [7]:
# Computes the sum of each column in Matrix AR (Royalty)
AR_col_weights = AR.sum(axis=0)

# Divides each column in Matrix AI by the sum of each Column in Matrix AR, columnwise.
AR_N = AR/AR_col_weights

# Computes the average of each row in Matrix AI_N, and returns a column vector.
AR_N_row_mean = np.mean(AR_N, axis=1)

# Returns the row vector that shows the mean of each column in AI after it is normalized. 
AR_N_row_mean

array([0.66666667, 0.33333333])

In [8]:
# Computes the sum of each column in Matrix AM (Marketing)
AM_col_weights = AM.sum(axis=0)

# Divides each column in Matrix AE by the sum of each Column in Matrix AE, columnwise.
AM_N = AM/AM_col_weights

# Computes the average of each row in Matrix AE_N, and returns a column vector.
AM_N_row_mean = np.mean(AM_N, axis=1)

# Returns the row vector that shows the mean of each column in AE after it is normalized. 
AM_N_row_mean

array([0.33333333, 0.66666667])

In [9]:
# Computes the sum of each column in Matrix AA (Advance)
AA_col_weights = AA.sum(axis=0)

# Divides each column in Matrix AR by the sum of each Column in Matrix AR, columnwise.
AA_N = AA/AA_col_weights

# Computes the average of each row in Matrix AR_N, and returns a column vector.
AA_N_row_mean = np.mean(AA_N, axis=1)

# Returns the row vector that shows the mean of each column in AR after it is normalized. 
AA_N_row_mean

array([0.5, 0.5])

In [10]:
# Creates Eigenvector matrix from each of the Eigenvectors from each attribute.
A_eig_matrix = np.array([AR_N_row_mean, AM_N_row_mean, AA_N_row_mean]).T
A_eig_matrix

array([[0.66666667, 0.33333333, 0.5       ],
       [0.33333333, 0.66666667, 0.5       ]])

In [11]:
# Computes final ranking from Eigenvector matrix and the criteria ranking vector.
# Results show that the author should pick publisher H since they have the highest score from the analysis.
Final_Decision = A_eig_matrix.dot(A_criteria_ranking_vect)
Final_Decision

array([[0.50191571],
       [0.49808429]])

In [12]:
# Consistency was not checked since it is guaranteed in a 2x2 matrix.