In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 0.25], 
              [0.5, 1, 0.2], 
              [4, 5, 1]])

AI = np.array([[1, 3, 4], 
               [0.333, 1, 0.2], 
               [0.25, 5, 1]])

AE = np.array([[1, 0.33, 2], 
               [3, 1, 0.5], 
               [0.5, 2, 1]])

AR = np.array([[1, 0.5, 1], 
               [2, 1, 0.5], 
               [1, 2, 1]])

In [3]:
# Computes the sum of each column in Matrix A
A_col_weights = A.sum(axis=0)
A_col_weights

array([5.5 , 8.  , 1.45])

In [4]:
# Divides each column in Matrix A by the sum of each Column in Matrix A, columnwise.
A_N = A/A_col_weights
A_N

array([[0.18181818, 0.25      , 0.17241379],
       [0.09090909, 0.125     , 0.13793103],
       [0.72727273, 0.625     , 0.68965517]])

In [5]:
# Computes the average of each row in Matrix A_N, and returns a column vector.
# This is the criteria ranking vector.
A_criteria_ranking_vect = (A_N.sum(axis=1)/3).reshape((3,1))
A_criteria_ranking_vect

array([[0.20141066],
       [0.11794671],
       [0.68064263]])

In [6]:
A_criteria_ranking_vect.sum()

1.0

In [7]:
# Computes the sum of each column in Matrix AI (Interview)
AI_col_weights = AI.sum(axis=0)

# Divides each column in Matrix AI by the sum of each Column in Matrix AI, columnwise.
AI_N = AI/AI_col_weights

# Computes the average of each row in Matrix AI_N, and returns a column vector.
AI_N_row_mean = np.mean(AI_N, axis=1)

# Returns the row vector that shows the mean of each column in AI after it is normalized. 
AI_N_row_mean

array([0.57809201, 0.11997758, 0.30193041])

In [8]:
# Computes the sum of each column in Matrix AE (Experience)
AE_col_weights = AE.sum(axis=0)

# Divides each column in Matrix AE by the sum of each Column in Matrix AE, columnwise.
AE_N = AE/AE_col_weights

# Computes the average of each row in Matrix AE_N, and returns a column vector.
AE_N_row_mean = np.mean(AE_N, axis=1)

# Returns the row vector that shows the mean of each column in AE after it is normalized. 
AE_N_row_mean

array([0.2975833 , 0.36994137, 0.33247533])

In [9]:
# Computes the sum of each column in Matrix AR (References)
AR_col_weights = AR.sum(axis=0)

# Divides each column in Matrix AR by the sum of each Column in Matrix AR, columnwise.
AR_N = AR/AR_col_weights

# Computes the average of each row in Matrix AR_N, and returns a column vector.
AR_N_row_mean = np.mean(AR_N, axis=1)

# Returns the row vector that shows the mean of each column in AR after it is normalized. 
AR_N_row_mean

array([0.26428571, 0.32857143, 0.40714286])

In [10]:
# Creates Eigenvector matrix from each of the Eigenvectors from each attribute.
A_eig_matrix = np.array([AI_N_row_mean, AE_N_row_mean, AR_N_row_mean]).T
A_eig_matrix

array([[0.57809201, 0.2975833 , 0.26428571],
       [0.11997758, 0.36994137, 0.32857143],
       [0.30193041, 0.33247533, 0.40714286]])

In [11]:
# Computes final ranking from Eigenvector matrix and the criteria ranking vector.
# Results show that the company should hire Maisa since they have the highest score from the analysis.
Final_Decision = A_eig_matrix.dot(A_criteria_ranking_vect)
Final_Decision

array([[0.33141699],
       [0.29143785],
       [0.37714516]])

In [12]:
def consistency(A, R):
    '''
    Computes the Consistency Ratio.
    
    Input: 
        Pairwise Comparision Matrix (A)
        Criteria Ranking Vector of A (R)
    Output:
        Scaler value of the Consistency Ratio.
    '''
    n_max_A = A.dot(R).sum()
    CI_A = (n_max_A - A.shape[0]) / (A.shape[0] - 1)
    RI_A = (1.98*(A.shape[0] - 2)) / (A.shape[0])

    CR_A = CI_A / RI_A
    
    return CR_A

In [13]:
CR_AI = consistency(A=AI, R=A_criteria_ranking_vect)
CR_AI

1.4543145008074476

In [14]:
CR_AE = consistency(A=AE, R=A_criteria_ranking_vect)
CR_AE

0.5161816044457107

In [15]:
CR_AR = consistency(A=AR, R=A_criteria_ranking_vect)
CR_AR

-0.060558563693360115