In [1]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB, MultinomialNB, CategoricalNB
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.metrics import confusion_matrix, accuracy_score
import numpy as np

In [2]:
df = pd.read_csv('problem-3-data.csv')
one = OneHotEncoder()
#clf = GaussianNB()
clf = MultinomialNB()
#clf = CategoricalNB
df_copy = df.copy()

In [3]:
def transformLabel(x):
    if x == 'Yes':
        return 1
    else:
        return 0

In [4]:
df_copy['label'] = df_copy['disease'].apply(transformLabel)
col_list = df_copy.columns.tolist()
col_list[1:-2]

['hbp', 'bmi', 'drink', 'weight']

In [5]:
col_list

['table', 'hbp', 'bmi', 'drink', 'weight', 'disease', 'label']

In [6]:
col_transform = make_column_transformer(
    (one, col_list[1:-2]),
    remainder='passthrough')
col_transform

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder', OneHotEncoder(),
                                 ['hbp', 'bmi', 'drink', 'weight'])])

In [7]:
data_transformed = col_transform.fit_transform(df_copy)

In [8]:
X = data_transformed[:,:10]
y_ = data_transformed[:,12:]
y = np.array([y_[each][0] for each in range(len(y_))])
y

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1])

In [9]:
X_hbp = X[:,:2]
X_bmi = X[:,2:5]
X_drink = X[:,5:7]
X_weight = X[:,7:]

In [10]:
X_hbp

array([[0.0, 1.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [0.0, 1.0]], dtype=object)

In [11]:
X_bmi

array([[0.0, 0.0, 1.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0]], dtype=object)

In [12]:
X_drink

array([[1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0]], dtype=object)

In [13]:
X_weight

array([[0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0]], dtype=object)

In [14]:
X_train = X[:14,:]
y_train = y[:14]
X_test = X[14:,:]
y_test = y[14:]

clf.fit(X_train, y_train)
y_pred_class = clf.predict(X_test)

confusion_matrix(y_test, y_pred_class)

array([[0, 1],
       [0, 4]])

In [15]:
accuracy_score(y_test, y_pred_class)

0.8